In [3]:
## Numpy array op

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing:", arr[2:7])
print("With step: ", arr[1:8:2])
print("Negative index: ", arr[-3])

Basic slicing: [3 4 5 6 7]
With step:  [2 4 6 8]
Negative index:  7


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific ele: ", arr_2d[1,2])
print("Entire row: ", arr_2d[1])
print("Entire col: ", arr_2d[:, 1])

Specific ele:  6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


## Sorting

In [7]:
unsorted= np.array([5,3,1,2,4,6,8,7,9])
print("sorted Arr: ", np.sort(unsorted))
unsorted_2D= np.array([[4,2],[1,3],[9,1]])
print("sorted 2D Arr: ", np.sort(unsorted_2D, axis=0)) #col
print("sorted 2D Arr: ", np.sort(unsorted_2D, axis=0)) #row

sorted Arr:  [1 2 3 4 5 6 7 8 9]
sorted 2D Arr:  [[1 1]
 [4 2]
 [9 3]]
sorted 2D Arr:  [[1 1]
 [4 2]
 [9 3]]


## Filtering

In [10]:
n = np.array([1,2,3,4,5,6,7,8,9])
f = [True, False, True, False, True, True, True, False, True]
print(n[f])

n = np.array([1,2,3,4,5,6,7,8,9])
even = n[n%2==0]
print(even)

[1 3 5 6 7 9]
[2 4 6 8]


## Filter with mask

In [9]:
mask  = n>5
print("numbers greater than 5: ",n[mask])

numbers greater than 5:  [6 7 8 9]


## Fancy indexing vs np.where()

In [12]:
indices = [0,2,4]
print(n[indices])

[1 3 5]


## Adding and removing data

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
concat= np.concatenate((arr1,arr2))
print(concat)

[1 2 3 4 5 6]


## array compatibility

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6,0])
c=np.array([7,8,9])

print("compatibility shapes, ", a.shape == b.shape)
print("compatibility shapes, ", a.shape == c.shape)

compatibility shapes,  False
compatibility shapes,  True


## deletion in numpy

In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.delete(arr, 2)
print(arr)

[1 2 4 5 6 7 8 9]
