## Numpy basics

In [ ]:
import numpy as np

### creating array from list

In [ ]:
arr1d=np.array([1,2,3,4,5])
print(f"Linear Arr: {arr1d}")
arr2d=np.array([[1,2,3],[4,5,6]])
print(f"2D Arr: \n {arr2d}")


Linear Arr: [1 2 3 4 5]
2D Arr: 
 [[1 2 3]
 [4 5 6]]


### list vs numpy arr

In [ ]:
pyList = [1,2,3]
print(f"pyList: {pyList*2}")
npArr = np.array([1,2,3]) # element wise mx
print(f"npArr: {npArr*2}")

pyList: [1, 2, 3, 1, 2, 3]
npArr: [2 4 6]


In [ ]:
### time comp vs list vs numpy arr
import time

start = time.time()
py_list=[i*2 for i in range(10000000)]
print(f"list op time: {time.time()-start}")

start = time.time()
np_arr=np.array(1000000)*2
print(f"np arr op time: {time.time()-start}")


list op time: 0.5900499820709229
np arr op time: 0.0001354217529296875


## Creating arr from scratch

In [ ]:
zeros = np.zeros((3,4))
print("zeros arr: \n", zeros)
ones = np.ones((3,4))
print("ones arr: \n", ones)

full = np.full((3,4), 5)
print("full arr: \n", full)

random = np.random.random((3,4))
print("random arr: \n", random)

sequence= np.arange(0, 11, 2)
print("sequence arr: \n", sequence)

zeros arr: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones arr: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full arr: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random arr: 
 [[0.92494417 0.68458899 0.10409991 0.84141544]
 [0.79910233 0.98560208 0.79615289 0.84252187]
 [0.31963123 0.27967097 0.0798811  0.75690157]]
sequence arr: 
 [ 0  2  4  6  8 10]


### Vector Matrix Tensor

In [ ]:
vector = np.array([1,2,3])
print("vector: \n", vector)
matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", matrix)
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("tensor: \n", tensor)

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape: ", arr.shape)
print("size: ", arr.size)
print("dtype: ", arr.dtype)
print("dimentions: ", arr.ndim)

shape:  (2, 3)
size:  6
dtype:  int64
dimentions:  2


### Array Reshaping

In [ ]:
arr=np.arange(12)
print("Original arr: ", arr)

reshaped = arr.reshape(3,4)
print("Reshaped arr: \n ", reshaped)

flattened = reshaped.flatten()
print("Flattened arr: ", flattened)

transposed = reshaped.T
print("Transposed arr: \n ", transposed)

#ravel return view, instead of copy
raveled = reshaped.ravel()
print("Raveled arr: ", raveled)

Original arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped arr: 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed arr: 
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
