In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
arr1=np.array([[1,2],[3,4]])
arr2=np.random.rand(3,3)
arr3=np.zeros((4,4))

print(arr1)
print(arr2)
print(arr3)

np.save('arr1.npy', arr1)
np.save('arr2.npy', arr2)
np.save('arr3.npy', arr3)

loaded_arr1 = np.load('arr1.npy')
loaded_arr2 = np.load('arr2.npy')
loaded_arr3 = np.load('arr3.npy')

print(loaded_arr1)
print(loaded_arr2)
print(loaded_arr3)

[[1 2]
 [3 4]]
[[0.48664532 0.4074292  0.9083334 ]
 [0.00481635 0.47824139 0.83044261]
 [0.1411704  0.79756056 0.63047391]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 2]
 [3 4]]
[[0.48664532 0.4074292  0.9083334 ]
 [0.00481635 0.47824139 0.83044261]
 [0.1411704  0.79756056 0.63047391]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
